#!/usr/bin/env bash

function install_dotnet() {
  local BUILD_DIR="$1"
  local CACHE_DIR="$2"
  local CORE_VER="$3"
  local ZIP_NAME="dotnet-${CORE_VER}.tar.gz"

  echo "Dotnet sdk: $CORE_VER"
  if [ ! -f $CACHE_DIR/$ZIP_NAME ]; then
  local DOTNET_SDK_URL = "https://dotnetcli.blob.core.windows.net/dotnet/Sdk/$CORE_VER/dotnet-sdk-$CORE_VER-linux-x64.tar.gz"
      #local DOTNET_SDK_URL="https://download.visualstudio.microsoft.com/download/pr/886b4a4c-30af-454b-8bec-81c72b7b4e1f/d1a0c8de9abb36d8535363ede4a15de6/dotnet-sdk-3.0.100-linux-x64.tar.gz"

      echo "Download url: $DOTNET_SDK_URL"
      curl -sSL -o $CACHE_DIR/$ZIP_NAME $DOTNET_SDK_URL
  else
    echo "$ZIP_NAME from cache folder"
  fi

  mkdir -p ${BUILD_DIR}/.heroku/dotnet && tar zxf $CACHE_DIR/$ZIP_NAME -C ${BUILD_DIR}/.heroku/dotnet

  ln -s ${BUILD_DIR}/.heroku/dotnet /app
}

# https://github.com/ddollar/heroku-buildpack-apt
function topic() {
  echo "-----> $*"
}

function indent() {
  c='s/^/       /'
  case $(uname) in
    Darwin) sed -l "$c";;
    *)      sed -u "$c";;
  esac
}
